Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.boot_timeout = 600

    config.vm.define "woumechtS2" do |server|
      server.vm.hostname = "woumechtS2"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.name = "woumechtS2"
        vb.memory = "2048"
        vb.cpus = 2
      end
      server.vm.provision "shell", path: "scripts/setup.sh"
    end
  end